[package]
name = "hello_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "ebreak"
path = "src/bin/ebreak.rs"

[[bin]]
name = "wfi"
path = "src/bin/wfi.rs"
